### ISSUE TITLE
Licensing confusion

### ISSUE THREAD

**Issue by mcepl** [jenisys/parse_type#1]
1) `setup.py` says BSD (does it means [BSD 3Clause](http://opensource.org/licenses/BSD-3-Clause) or [Simplified BSD 2Clause](http://opensource.org/licenses/BSD-2-Clause)?) but OK let’s say this ambiguity can be clarified because you attached 3Clause BSD License in the `LICENSE` file. It would be nice to clarify though (what about URL to the explicit text of license?). Anyway, that isn't the big deal.
2) What’s a little bit worse is https://github.com/jenisys/parse_type/blob/master/parse_type/__init__.py which is the only program file having a license header and this is clearly [MIT/X11 License](http://opensource.org/licenses/MIT)

Could you please clarify which BSD license you use (in README or program headers), and then make sure that program files contain only the appropriate license headers? (and they should have some)

Thank you

**Comment by ignatenkobrain** [comment]
any news here? or it's dead?

**Comment by pokiz** [comment]
+1

**Comment by jenisys** [comment]
FIXED IN: v0.6.1

* Switch to MIT license (same as: `parse` module)
* Use SPDX-License-Identifier in source code (and remove license text copy there)
