### ISSUE TITLE
Feature: Cardinality field support for built-in data types (or at least most)

### ISSUE THREAD

**Issue by jenisys** [jenisys/parse_type#10]
RELATED TO: #9

Currently, the cardinality field is only supported for user-defined data types.
It would be nice to extend the functionality to built-in data types that are provided by the ``parse`` module. Sadly, this means that relevant parts need to be extracted from the ``parse`` module and provided in a way that is usable to ``parse_type``, meaning a type converter function for each data type with the associated information (pattern, name, regex group_count, etc.).

**Comment by priyacshah** [comment]
I am facing the same issue with the Radish framework as below. 
https://github.com/radish-bdd/radish/issues/130

**Comment by jenisys** [comment]
The workaround is pretty simple.
Just define a user-defined type and you get what you want.

BACKGROUND:
The regex-patterns for the builtin datatypes are deeply embedded and directly accessible to users of the `parse` module.
