### ISSUE TITLE
setup.py should pin parse <= 1.13.0 to keep python2.7 support or drop the python 2 support...

### ISSUE THREAD

**Issue by omit66** [jenisys/parse_type#15]
parse 1.13.0  is the latest version, which supports python2.7:
https://pypi.org/project/parse/1.13.0/

**Comment by jenisys** [comment]
Yes, I could do that, but:

* This should be the responsibility of the `parse` module setup.py (Richard Jones)
* The test suite of the `parse` module and `parse-type` run without any problems also with newer versions of `parse` for Python 2.7
