### ISSUE TITLE
Outdated CHANGES.txt

### ISSUE THREAD

**Issue by The-Compiler** [jenisys/parse_type#18]
Despite the last release apparently [being v0.6.0](https://github.com/jenisys/parse_type/releases/tag/v0.6.0), it looks like there's a [CHANGES.txt](https://github.com/jenisys/parse_type/blob/master/CHANGES.txt) in this repo, which claims:

> Version: 0.4.3 (2018-04-xx, unreleased)

**Comment by jenisys** [comment]
OOPS, I must have overlooked it.
Thx for the reminder.
I will fix it soon.
