### ISSUE TITLE
Create PyPI release

### ISSUE THREAD

**Issue by timofurrer** [jenisys/parse_type#6]
Is it possible to create a PyPI release?

I'd need the newest `parse==1.8.0`.

Thanks! :beers:

**Comment by timofurrer** [comment]
What's the benefit of vendoring `parse` in this case?
I'd see the *[abstractness](https://caremad.io/posts/2013/07/setup-vs-requirement/)* of the `parse` dependency a benefit. You could always fall back to a vendored version of `parse` ..

**Comment by timofurrer** [comment]
Anything which needs to be done before you can release? Maybe I can help with that ..

**Comment by timofurrer** [comment]
I've forked and mirrored the package on PyPI. 

Please ping me when you've updated this package on PyPI ...

**Comment by jenisys** [comment]
RELEASED: parse_type-0.4.1 (with parse-1.8.2)
